### ISSUE TITLE
Some changes visible in the dummy app do not display when used as a dependency elsewhere

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/django-admin-508#18]
https://github.com/raft-tech/TANF-app/pull/1664#pullrequestreview-899550997

To quote the relavent part of this review for this issue:

- Error counter (shown in video) is working to provide context into the number of errors on a page—however in both Chrome and Safari on MacOS the alert attached to it seems to be getting overridden by other page events about half the time. If we can, I suggest trying to set focus to the error counter on reload so that if it doesn't get read as an alert it still gets read as text. This also matches frontend TDP behavior on form errors.
- AC 1 isn't implemented at the moment, so generic "Field is required" vs "[Specific Field name] is required" errors are still present. All form fields do a good job of only allowing valid content to be entered, and they do pass "Required" and "Invalid" states to VoiceOver so from a pure compliance standpoint we might be able to do without the specific error copy, however a follow on discussion of whether there's an efficient way to get this done would be great.

# Tasks

- [ ] figure out why required field validation works in dummy app and not in TDRS/dependent applications
- [ ] Try setting focus to error counter

# Acceptance Criteria

- [ ] Screen Reader consistantly reads error
- [ ] Name of field being present in required field validation error works in tdrs

**Comment by riatzukiza** [comment]
View of it working in mysite dummy app in da508 development space:
![image](https://user-images.githubusercontent.com/10676925/158190459-1b7a1300-bd97-48b7-b3a4-1d07a26f82a6.png)

**Comment by riatzukiza** [comment]
This is solved, tdrs doesn't allow inline scripts, but by default they are fine. Just had to remove the inlinescript
